version: 2.1
commands:
  set_up_environment:
    description: "Set up testing environment"
    parameters:
      cache_key:
        type: string
        default: shade-stable-cache
    steps:
      - run: set -e
      - setup_remote_docker
      - run:
          name: Prepare environment and install dependencies
          command: |
            export SCCACHE_CACHE_SIZE=200M
            export WORK_DIR="$CIRCLE_WORKING_DIRECTORY/.cache/sccache"
            export SCCACHE_DIR="$CIRCLE_WORKING_DIRECTORY/.cache/sccache"
            mkdir -p "$CIRCLE_WORKING_DIRECTORY/.bin"
            wget https://github.com/mozilla/sccache/releases/download/0.2.13/sccache-0.2.13-x86_64-unknown-linux-musl.tar.gz
            tar -C "$CIRCLE_WORKING_DIRECTORY/.bin" -xvf sccache-0.2.13-x86_64-unknown-linux-musl.tar.gz
            mv $CIRCLE_WORKING_DIRECTORY/.bin/sccache-0.2.13-x86_64-unknown-linux-musl/sccache $CIRCLE_WORKING_DIRECTORY/.bin/sccache
            export PATH="$PATH:$CIRCLE_WORKING_DIRECTORY/.bin"
            export RUSTC_WRAPPER="sccache"
            rm -rf "$CIRCLE_WORKING_DIRECTORY/.cargo/registry"
            sudo apt-get update && sudo apt-get install -y build-essential clang binaryen make libssl-dev libssl-dev
      - restore_cache:
          keys:
            - << parameters.cache_key >>
  clear_environment:
    description: "Clear environment"
    parameters:
      cache_key:
        type: string
        default: shade-stable-cache
    steps:
      - run: (sccache -s||true)
      - run: set +e
      - save_cache:
          key: << parameters.cache_key >>
          paths:
            - .cache/sccache
            - .cargo
  install_rust_nightly:
    description: "Install Rust nightly toolchain"
    steps:
      - run:
          command: |
            rustup toolchain install nightly-x86_64-unknown-linux-gnu

jobs:
  tests:
    docker:
      - image: cimg/rust:1.56.1
    steps:
      - checkout
      - set_up_environment:
          cache_key: shade-stable-cache
      - run:
          name: Build and run tests
          no_output_timeout: 35m
          command: |
            make
      - clear_environment:
          cache_key: shade-stable-cache

  fmt:
    docker:
      - image: cimg/rust:1.56.1
    steps:
      - checkout
      - install_rust_nightly
      - set_up_environment:
          cache_key: shade-fmt-cache
      - run:
          name: Check style
          no_output_timeout: 35m
          command: cargo +nightly fmt --all -- --check
      - clear_environment:
          cache_key: shade-fmt-cache

  clippy:
    docker:
      - image: cimg/rust:1.56.1
    steps:
      - checkout
      - install_rust_nightly
      - set_up_environment:
          cache_key: shade-clippy-cache
      - run:
          name: Check style
          no_output_timeout: 35m
          command: cargo +nightly clippy --workspace --all-targets
      - clear_environment:
          cache_key: shade-clippy-cache

workflows:
  main-workflow:
    jobs:
      - tests
      - fmt
      - clippy
